name: SkyKing CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_skyking
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-cov pytest-flask
    
    - name: Set environment variables for testing
      run: |
        echo "DB_HOST=localhost" >> $GITHUB_ENV
        echo "DB_NAME=test_skyking" >> $GITHUB_ENV
        echo "DB_USER=postgres" >> $GITHUB_ENV
        echo "DB_PASSWORD=postgres" >> $GITHUB_ENV
        echo "DB_PORT=5432" >> $GITHUB_ENV
        echo "FLASK_SECRET_KEY=test_secret_key_for_ci" >> $GITHUB_ENV
        echo "FLASK_FERNET_KEY=test_fernet_key_base64_encoded" >> $GITHUB_ENV
    
    - name: Run linting (flake8)
      run: |
        pip install flake8
        # Stop the build if there are Python syntax errors or undefined names
        flake8 app --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit-zero treats all errors as warnings
        flake8 app --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      continue-on-error: true
    
    - name: Run unit tests
      run: |
        pytest tests/unit/ -v --cov=app --cov-report=xml --cov-report=html
      continue-on-error: true
    
    - name: Run integration tests
      run: |
        pytest tests/integration/ -v
      continue-on-error: true
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
      continue-on-error: true
    
    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          htmlcov/
          coverage.xml

  build:
    name: Build and Verify
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Verify application structure
      run: |
        python verify_system.py
      continue-on-error: true
    
    - name: Check for security vulnerabilities
      run: |
        pip install safety
        safety check --json
      continue-on-error: true
    
    - name: Build success notification
      if: success()
      run: echo "✅ Build completed successfully!"
    
    - name: Build failure notification
      if: failure()
      run: echo "❌ Build failed. Check logs above."

  deploy:
    name: Deploy (if on main)
    runs-on: ubuntu-latest
    needs: [test, build]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Deploy placeholder
      run: |
        echo "🚀 Deployment would happen here"
        echo "This is where you would deploy to your server"
        echo "For example: SSH to server and pull latest code"
    
    - name: Deployment notification
      run: echo "✅ Deployment completed (placeholder)"
